// sequence.h - iterators having operator bool
#pragma once

#include "array.h"
#include "back.h"
#include "binop.h"
#include "concatenate.h"
#include "constant.h"
#include "counted.h"
#include "drop.h"
#include "epsilon.h"
#include "factorial.h"
#include "flatten.h"
#include "fmap.h"
#include "fold.h"
#include "length.h"
#include "null.h"
#include "pointer.h"
#include "power.h"
#include "reverse.h"
#include "scan.h"
#include "sequence.h"
#include "singleton.h"
#include "take.h"
#include "tuple.h"